# Generated by Django 4.1 on 2022-08-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flower",
            fields=[
                (
                    "name",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=150)),
                ("frequency", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("last_watering", models.DateField()),
                ("next_watering", models.DateField()),
            ],
        ),
    ]
